### ISSUE TITLE
Case searching

### ISSUE THREAD

**Issue by dracos** [mysociety/noiseworks#24]
There are search boxes in the prototype - how should they work, what should they search?
Postcode seems obvious one, geolocation, general addresses, people's names?

If matches a postcode - show all addresses in postcode, or all addresses with cases in that postcode, or something else?

**Comment by dracos** [comment]
What do staff want to search on?
Names - use unaccent extension?
FTS easy enough to add, but on what? Is names and location searches enough?

**Comment by LouiseMySociety** [comment]
@zarino can you provide clarification to Matthew's questions above please?

**Comment by zarino** [comment]
In rough order of importance, based on what we heard during discovery and alpha:

1. show cases (hopefully just the one!) with the given case reference number
1. show cases at the given partial address (eg: `11 Example Street` or `Example Street`) or postcode
1. show cases involving the given complainant or perpetrator (by person’s name)
1. show cases _near_ a given geographic point (ie: a geolocated address or postcode)

That fourth use case only came up in one situation, and that’s when you’re searching for "duplicate" reports – ie: other reports near this one, which might also have the same category. So, even though number 4 is fairly low priority, we might want to enable it, because it could be part of the workflow for merging one case into another – eg: click the merge button on case A, then search for nearby cases (optionally with the same category), and then click the "merge into" button on the chosen case B.

**Comment by dracos** [comment]
A search exists and searches ID, free text fields (including location cache so should work for street/postcode search), names, etc. Nearby - that's only shown as part of the merge flow, so hopefully that's enough for the moment.
